### ISSUE TITLE
MALWARE DETECTED

### ISSUE THREAD

**Issue by THEMADPROFdj** [jd-13/MONSTR-Stereo-Imaging#27]
Download Link:: https://github.com/jd-13/wea-releases/releases/download/monstr-v2.1.2/MONSTR.v2.1.2.zip

Detection Link:https://www.filescan.io/uploads/6631c9ddca951b8594594ebf
 I hope that you can explain/resolve.

**Comment by jd-13** [comment]
Hi, thanks for reporting.

Everything that's listed under `Suspicious` in the [MONSTR.vst3](https://www.filescan.io/uploads/6631c9ddca951b8594594ebf/reports/4ea5e06b-094e-434b-aff0-d6279f509180/overview) looks like basic functionality of the [JUCE](https://juce.com/) library. This is used to build most audio plugins, and provides functions for things like navigating the file system, starting/stopping processes, etc.

Everything that's listed under `Maclicious` is actually just from a font file that's embedded in the plugin. The file comes from [this repo](https://github.com/JulietaUla/Montserrat/tree/master), specifically [Montserrat-Regular.ttf](https://github.com/JulietaUla/Montserrat/blob/master/fonts/ttf/Montserrat-Regular.ttf).

If you download that file and upload it for analysis, it returns the [same result](https://www.filescan.io/uploads/66322b07de9c2e31030621c8/reports/fb188c84-1b32-41bb-a32a-e698710d28d0/overview). I can't be sure as I don't know how their detection works, but I assume it's misinterpreting some strings in the ttf as URLs, and treating anything ending in .sc ([wiki](https://en.wikipedia.org/wiki/.sc)) as malicious.

And if you upload [this](https://fonts.google.com/specimen/Montserrat) version of the font file as provided by Google, you'll also get the [same result](https://www.filescan.io/uploads/66322d84de9c2e3103062545/reports/8f8b55a8-9dff-4191-a9e3-b8d38d46538f/overview) again.

**Comment by jd-13** [comment]
Closing as there's no action needed, let me know if you have any more questions or issues

**Comment by THEMADPROFdj** [comment]
Thank You for responding. Due to my budget (or lack there of), I'm still operating on Windows 7 Professional on a 2010 HP laptop. So I have to be extra diligent. I usually run with Linux distros. But the sheer amount of VST plugins and hosts (using stand alone Pedalboard2) for Windows makes it worth the ever present risk. Thanks verifying your code. I'm still learning, so, hence a little paranoid.
